version: '3.8'

services:
  postgres:
    container_name: nflow-assistant-db
    image: postgres:14-alpine
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 128Mb
    ports:
      - '5432:5432'
    command: -c shared_buffers=500MB -c fsync=off
    environment:
      POSTGRES_USER: ${PGUSER:-pg}
      POSTGRES_PASSWORD: ${PGPASSWORD:-pg}
      POSTGRES_DB: ${PGDATABASE:-}
    healthcheck:
      start_period: 5s
      test: 'pg_isready'
    volumes:
      - nflow-assistant_pg_data:/var/lib/postgresql/data
    networks:
      - nflow-assistant

  redis:
    container_name: nflow-assistant-redis
    image: redis:latest
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - '6379:6379'
    volumes:
      - nflow-assistant_redis_data:/data
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-redis}
    networks:
      - nflow-assistant

networks:
  nflow-assistant:

volumes:
  nflow-assistant_pg_data:
    driver: local
  nflow-assistant_redis_data:
    driver: local
