version: '3.8'

services:
  postgres:
    container_name: nflow-assistant-db-dev
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${PGUSER:-pg}
      POSTGRES_PASSWORD: ${PGPASSWORD:-pg}
      POSTGRES_DB: ${PGDATABASE:-nflow-chat-assistant}
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 5
      test: ['CMD-SHELL', 'pg_isready -U ${PGUSER:-pg} -d postgres']
    volumes:
      - nflow-assistant_pg_data_dev:/var/lib/postgresql/data
    networks:
      - nflow-assistant

  redis:
    container_name: nflow-assistant-redis-dev
    image: redis:latest
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - nflow-assistant_redis_data_dev:/data
    command: redis-server --requirepass ${REDIS_PASSWORD:-redis}
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - nflow-assistant

  api:
    container_name: nflow-assistant-api-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - nflow-assistant

networks:
  nflow-assistant:

volumes:
  nflow-assistant_pg_data_dev:
    driver: local
  nflow-assistant_redis_data_dev:
    driver: local
